[build]
  command = "npm run build"  # Your appropriate build command
  publish = "client/public"   # Your publish directory

[build.environment]
  PYTHON_VERSION = "3.8"  # Specify the Python version

# Consolidate plugins into a single section
[[plugins]]
  package = "@netlify/plugin-lifecycle"
  inputs = { 
    lifecycle = { 
      preBuild = """
        apt-get update && apt-get install -y libpq-dev
      """
    }
  }

[[plugins]]
  package = "@netlify/plugin-nextjs"  # Keeping this plugin as is